// Generated by Dagger (https://google.github.io/dagger).
package com.kalay.component.ui.slider;

import dagger.internal.Factory;

public final class SliderViewHolder_BinderFactory_Factory
    implements Factory<SliderViewHolder.BinderFactory> {
  private static final SliderViewHolder_BinderFactory_Factory INSTANCE =
      new SliderViewHolder_BinderFactory_Factory();

  @Override
  public SliderViewHolder.BinderFactory get() {
    return new SliderViewHolder.BinderFactory();
  }

  public static SliderViewHolder_BinderFactory_Factory create() {
    return INSTANCE;
  }

  public static SliderViewHolder.BinderFactory newInstance() {
    return new SliderViewHolder.BinderFactory();
  }
}
