// Generated by Dagger (https://google.github.io/dagger).
package com.kalay.component.ui.slider;

import dagger.internal.Factory;

public final class SliderViewHolder_HolderFactory_Factory
    implements Factory<SliderViewHolder.HolderFactory> {
  private static final SliderViewHolder_HolderFactory_Factory INSTANCE =
      new SliderViewHolder_HolderFactory_Factory();

  @Override
  public SliderViewHolder.HolderFactory get() {
    return new SliderViewHolder.HolderFactory();
  }

  public static SliderViewHolder_HolderFactory_Factory create() {
    return INSTANCE;
  }

  public static SliderViewHolder.HolderFactory newInstance() {
    return new SliderViewHolder.HolderFactory();
  }
}
